# Generated by Django 4.1.5 on 2023-01-19 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='插入时间')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('status', models.CharField(choices=[('disable', '停用'), ('available', '可用'), ('using', '使用中')], default='available', max_length=16, verbose_name='状态')),
                ('update_time', models.DateTimeField(verbose_name='最近更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(verbose_name='最近更新时间')),
                ('time_begin', models.DateTimeField(verbose_name='开始时间')),
                ('time_end', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meetingroom')),
            ],
            options={
                'db_table': 'meeting_record',
            },
        ),
    ]
